services:
    agent:
        image: apr_core:dev
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/workspace
        env_file:
            -   ./.env
            - ./.docker-env-issues
        environment:
            CONFIG_FILE: /workspace/workspace/config/bugfix.yml
#        entrypoint: ["sh", "-c", "tail -f /dev/null"] #for attaching and debugging
