services:
    apr_core:
        image: apr_core:dev
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/workspace
        env_file:
            -   ./.env
            - ./.docker-env-issues
        environment:
            CONFIG_FILE: /workspace/workspace/config/bugfix.yml