services:
    agent:
        image: bugfix-ci:dev
        build:
            context: ..
            dockerfile: docker/Dockerfile
        volumes:
            - ../workspace/:/workspace
        env_file:
            -   ../.env
        environment:
            CONFIG_FILE: /workspace/config/bugfix.yml
#        entrypoint: ["sh", "-c", "tail -f /dev/null"] #for attaching and debugging
