name: BugFix Agent
on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: "30 3 * * *"

jobs:
  bugfix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: read
    steps:
      - uses: actions/checkout@v4

      - name: Pull latest image
        run: docker pull ghcr.io/justingebert/bugfix-ci:latest

      - name: Run agent
        env:
          GITHUB_TOKEN:   ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run --rm \
            ghcr.io/justingebert/bugfix-ci:latest
