name: BugFix Agent
on:
  workflow_dispatch: {}
#  pull_request:
#    types: [ opened, edited ]
#  issues:
#    types: [ opened, edited, labeled ]
  # schedule:
  #   - cron: "30 3 * * *"

jobs:
  bugfix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: read
    steps:
      - uses: actions/checkout@v4

      - name: Pull latest image
        run: docker pull ghcr.io/justingebert/bugfix-ci:latest

      - name: Run agent
        env:
          GITHUB_TOKEN:   ${{ secrets.GITHUB_TOKEN }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: |
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/workspace" \
            ghcr.io/your-user/bugfix-agent:latest
